import { test, expect } from '@playwright/test'

async function navigate(page, label) {
  if (await page.getByRole('button', { name: 'Open navigation' }).isVisible()) await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('navigation', { name: 'Main navigation' }).filter({ visible: true }).getByRole('button', { name: label, exact: false }).click()
}
test('engineering workflow, edits, persistence, audit and downloads', async ({ page }) => {
  const exceptions = []
  page.on('pageerror', error => exceptions.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Compare materials. Understand the load.')
  await page.getByRole('button', { name: 'Run comparison', exact: true }).first().click()
  await expect(page.locator('.hero-number')).toContainText('128.3')
  await expect(page.locator('.result-hero')).toContainText('Timber frame')
  await expect(page.locator('.result-hero')).toContainText('15:00')
  await page.getByLabel('Design hour', { exact: true }).selectOption('19')
  await page.getByLabel('Audit assembly', { exact: true }).selectOption({ label: 'Insulated concrete' })
  await expect(page.locator('.formula-box')).toContainText('Q = 147.375 W')
  await page.getByLabel('Chart metric').selectOption('correctedCLTD')
  await page.locator('.chart-legend').getByRole('button', { name: /Timber frame/ }).click()
  await expect(page.locator('.chart-legend').getByRole('button', { name: /Timber frame/ })).toHaveAttribute('aria-pressed', 'false')
  await navigate(page, 'Materials')
  await page.getByRole('button', { name: 'Edit Timber frame', exact: true }).click()
  await page.getByLabel('U-value', { exact: false }).fill('0.7')
  await page.getByRole('button', { name: 'Save assembly' }).click()
  await navigate(page, 'Results')
  await expect(page.getByText('Inputs have changed.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Run comparison', exact: true }).click()
  await expect(page.locator('.result-hero')).toContainText('Insulated concrete')
  await navigate(page, 'Materials')
  await page.getByRole('button', { name: 'Duplicate Timber frame', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Timber frame (copy)', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete Timber frame (copy)', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Delete Timber frame (copy)', exact: true }).click()
  await page.getByRole('button', { name: 'Delete assembly', exact: true }).click()
  await navigate(page, 'Settings')
  await page.getByLabel('Project name', { exact: true }).fill('Verified persistence workflow')
  await expect(page.getByRole('status')).toContainText('Saved locally')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export project JSON', exact: true }).click()
  const exported = await downloadPromise
  await expect(exported.suggestedFilename()).toBe('thermacompare-project.json')
  const projectPath = await exported.path()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Verified persistence workflow' })).toBeVisible()
  await navigate(page, 'Settings')
  await page.getByLabel('Import project JSON', { exact: true }).setInputFiles(projectPath)
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Verified persistence workflow' })).toBeVisible()
  await navigate(page, 'Reports')
  const csvPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Summary CSV', exact: true }).click()
  expect((await csvPromise).suggestedFilename()).toBe('comparison-summary.csv')
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.demo-warning')).toBeVisible()
  await page.pdf({ path: 'test-results/sample-report.pdf', format: 'A4', landscape: true, printBackground: true })
  expect(exceptions).toEqual([])
})

test('reference templates import in JSON and CSV; missing combinations block', async ({ page }) => {
  await page.goto('/')
  await navigate(page, 'Reference data')
  for (const type of ['JSON', 'CSV']) {
    const promise = page.waitForEvent('download')
    await page.getByRole('button', { name: `${type} template`, exact: true }).click()
    const download = await promise
    const path = await download.path()
    const { readFile } = await import('node:fs/promises')
    await page.getByLabel('Import reference dataset').setInputFiles({ name: `reference.${type.toLowerCase()}`, mimeType: type === 'JSON' ? 'application/json' : 'text/csv', buffer: await readFile(path) })
    await expect(page.locator('.dataset-item')).toHaveCount(type === 'JSON' ? 2 : 3)
  }
  await page.getByLabel('Search reference rows').fill('Roof Horizontal 15')
  await expect(page.locator('.table-toolbar')).toContainText('7 entries')
  await navigate(page, 'Comparison setup')
  await page.getByRole('button', { name: 'Roof', exact: true }).click()
  await expect(page.getByLabel('Orientation')).toBeDisabled()
  await expect(page.getByLabel('Orientation')).toHaveValue('Horizontal')
  await page.getByRole('button', { name: 'Run comparison', exact: true }).first().click()
  await expect(page.locator('.result-hero')).toBeVisible()
  await navigate(page, 'Comparison setup')
  await page.getByLabel('Site latitude').fill('41')
  await page.getByRole('button', { name: 'Run comparison', exact: true }).first().click()
  await expect(page.getByRole('alert')).toContainText('Missing LM')
  await page.getByLabel('Site latitude').fill('40')
  await page.getByRole('button', { name: 'IP · Imperial' }).click()
  await page.getByRole('button', { name: 'Run comparison', exact: true }).first().click()
  await expect(page.getByRole('alert')).toContainText('Dataset units must match')
})

for (const width of [1440, 1024, 768, 390]) {
  test(`all pages fit ${width}px; keyboard dialog access`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/')
    await page.getByRole('button', { name: 'Run comparison', exact: true }).first().click()
    for (const label of ['Comparison setup', 'Materials', 'Results', 'Reference data', 'Reports', 'Settings']) {
      await navigate(page, label)
      await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
      expect(overflow, `${label} at ${width}px`).toBe(false)
      await page.screenshot({ path: `test-results/${width}-${label.replaceAll(' ', '-')}.png`, fullPage: true })
    }
    await navigate(page, 'Materials')
    await page.getByRole('button', { name: 'Add assembly', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    const bounds = await page.getByRole('dialog').boundingBox()
    expect(bounds.width).toBeLessThanOrEqual(width - 20)
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await expect(page.getByRole('button', { name: 'Add assembly', exact: true })).toBeFocused()
  })
}
